### ISSUE TITLE
How to download the raw videos of Youcook2

### ISSUE THREAD

**Issue by tobeatraceur** [jacobswan1/Video_S3D_Talker#1]
Hi, thank you for sharing the code!

There are only 2D features on the Youcook2 website, so how did you download the raw videos?

Thank you!

**Comment by jacobswan1** [comment]
Hi there, thanks for your words.

So, unfortunately, the raw videos are released previously by Luowei and are not available anymore now as there exist some property limitations according to Luowei.

**Comment by tobeatraceur** [comment]
Thanks for your reply!
