### ISSUE TITLE
V2C-Generation and V2C-QA code

### ISSUE THREAD

**Issue by Muccul** [jacobswan1/Video_S3D_Talker#4]
Hi @jacobswan1 
thank you for your work!
Could you provide the V2C-Generation and V2C-QA code？

**Comment by jacobswan1** [comment]
Hi @Muccul, are you still looking for the generation codes? While regretfully we don't plan to further release the QA code yet.

**Comment by tangbing9922** [comment]
> Hi @Muccul, are you still looking for the generation codes? While regretfully we don't plan to further release the QA code yet.

thank you for your work！Could  you provide the relevant code of V2C-Generation later @jacobswan1
