### ISSUE TITLE
Testing on different dataset

### ISSUE THREAD

**Issue by Special256** [jacobswan1/Video_S3D_Talker#5]
Hello
Thanks for the work, I'm not good at programming so please let me know if this question is even necessary.
I have tried image captioning before and normally I can receive captions for any random image during testing, but how do I do the same for video captioning using your trained model? An example for this would help cause your dataset has no videos just the features and captions.

**Comment by jacobswan1** [comment]
Hi @Special256 , thanks for being interested in V2C. Unfortunately, I think the current implementation will not be able to extend to other datasets as it requires the pre-extraction of video features.

**Comment by Special256** [comment]
@jacobswan1 Thank you for the response
