### ISSUE TITLE
PPL indicator

### ISSUE THREAD

**Issue by Muccul** [jacobswan1/Video_S3D_Talker#6]
https://github.com/jacobswan1/Video2Commonsense/blob/4749848bfc13689d5e7724e62d9f074bce1b9d07/test.py#L78-L93

hi! @jacobswan1 
This PPL index calculates the index of a certain GT, not the PPL of the predicted sentence.
Why does this code work out as a value on paper?

**Comment by jacobswan1** [comment]
Hi @Muccul, thanks for pointing this error out. Indeed I just ran a quick test and found it does give the wrong PPL score. 

I'll address it and update the arxiv table accordingly later, while I think it does not invalidate the paper’s other claims yet. 

please stay tuned and I'm working on getting the correct ppl scores and update it soon.

ps: Many thanks again for letting me know! And also thanks Weijiang for forwarding this issue to me.

**Comment by jacobswan1** [comment]
Hi @Muccul, I've updated both PPL eval codes, also together with other re-implemented baseline numbers, and pre-trained checkpoint.
Again, I appreciate your help in pointing out the bug, and many thanks for your help. Many thanks!
